# Generated by Django 6.1 on 2026-08-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('host', 'Host'), ('organizer', 'Organizer')], default='player', max_length=16),
        ),
    ]
