# Generated by Django 6.1 on 2026-08-10 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking_per_match_user',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_status__in', ('pending', 'paid', 'waived'))), fields=('match', 'user'), name='unique_active_booking_per_match_user'),
        ),
    ]
