# Generated by Django 6.1 on 2026-08-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_unique_booking_per_match_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
