# Generated by Django 6.1 on 2026-08-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationlog_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='type',
            field=models.CharField(choices=[('otp_code', 'OTP code'), ('telegram_link', 'Telegram link'), ('booking_confirmed', 'Booking confirmed'), ('split_request', 'Split payment request'), ('match_reminder', 'Match reminder'), ('waitlist_filled', 'Waitlist filled'), ('split_expired', 'Split payment expired'), ('badge_unlocked', 'Badge unlocked'), ('topup_approved', 'Top-up approved')], max_length=32),
        ),
    ]
