# Generated by Django 6.1 on 2026-08-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notificationlog_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='type',
            field=models.CharField(choices=[('otp_code', 'OTP code'), ('telegram_link', 'Telegram link'), ('booking_confirmed', 'Booking confirmed'), ('split_request', 'Split payment request'), ('match_reminder', 'Match reminder'), ('waitlist_filled', 'Waitlist filled'), ('split_expired', 'Split payment expired'), ('badge_unlocked', 'Badge unlocked'), ('topup_approved', 'Top-up approved'), ('friend_request', 'Friend request'), ('friend_accepted', 'Friend request accepted'), ('match_invite', 'Match invite')], max_length=32),
        ),
    ]
