# Generated by Django 6.1 on 2026-08-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificationlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='type',
            field=models.CharField(choices=[('otp_code', 'OTP code'), ('telegram_link', 'Telegram link'), ('booking_confirmed', 'Booking confirmed'), ('split_request', 'Split payment request'), ('match_reminder', 'Match reminder'), ('waitlist_filled', 'Waitlist filled'), ('split_expired', 'Split payment expired'), ('badge_unlocked', 'Badge unlocked'), ('topup_approved', 'Top-up approved'), ('friend_request', 'Friend request'), ('friend_accepted', 'Friend request accepted'), ('match_invite', 'Match invite'), ('organizer_request_approved', 'Organizer request approved'), ('organizer_request_rejected', 'Organizer request rejected')], max_length=32),
        ),
    ]
